### ISSUE TITLE
Non-Required Fields

### ISSUE THREAD

**Issue by leviwilson** [dnasir/angular-dateParser#28]
I could be missing something, but I have the following:

```html
<input type="text" date-parser="M/d/yyyy" id="myDate" data-ng-model="dateText" />
<!-- ... -->
<button type="button" data-ng-disabled="form.$invalid">Submit</button>
```

I do _not_ have a `required` set on it so I expected that my `Submit` button would be enabled when I loaded my form, but it is not. In my example, the `ng-model` (`dateText`) is a string.

## Edit
I'm not sure this is the correct solution, but it fixed my issue. I think the `$parser` needs to return an empty string rather than `undefined` as well as not making it invalid if it is empty. This then worked as I expected in conjunction with the `ngRequired`.

```javascript
ngModel.$parsers.unshift(function(viewValue) {
  var date = $dateParser(viewValue, dateFormat);
                    
  // Set validity when view value changes
  ngModel.$setValidity('date', ngModel.$isEmpty(viewValue) || angular.isDate(date));

  return date || '';
});
```

**Comment by dnasir** [comment]
@leviwilson I'm going to close this issue for now. If my changes didn't fix your problem, feel free to reopen it.
