### ISSUE TITLE
Module name conflicting with AngularStrap

### ISSUE THREAD

**Issue by dekel** [dnasir/angular-dateParser#31]
Getting exceptions when working with the date input in AngularStrap and found that AngularStrap are using a module named "dateParser". Since the name it is so generic, I suggest you change the name to something more specific.
But great job with this util. Thanks!

**Comment by dnasir** [comment]
@dekel I think my module came before the one currently available in AngularStrap, but I'll keep it in mind. Thanks for letting me know.
