### ISSUE TITLE
$locale change at runtime

### ISSUE THREAD

**Issue by ardf69** [dnasir/angular-dateParser#32]
The module doesn't work if the $locale change at runtime. I changed the following code:

    } ]).factory("$dateParser", [ "$locale", "dateParserHelpers", function($locale, dateParserHelpers) {
        "use strict";
        var datetimeFormats = $locale.DATETIME_FORMATS;
        var monthNames = datetimeFormats.MONTH.concat(datetimeFormats.SHORTMONTH);
        var dayNames = datetimeFormats.DAY.concat(datetimeFormats.SHORTDAY);
        return function(val, format) {
            if (angular.isDate(val)) {
                return val;
            }

in

    } ]).factory("$dateParser", [ "$locale", "dateParserHelpers", function($locale, dateParserHelpers) {
        "use strict";
        return function(val, format) {
            var datetimeFormats = $locale.DATETIME_FORMATS;
            var monthNames = datetimeFormats.MONTH.concat(datetimeFormats.SHORTMONTH);
            var dayNames = datetimeFormats.DAY.concat(datetimeFormats.SHORTDAY);

            if (angular.isDate(val)) {
                return val;
            }

and

    angular.module("dateParser").directive("dateParser", [ "dateFilter", "$dateParser", function(dateFilter, $dateParser) {
        "use strict";
        return {
            restrict: "A",
            require: "ngModel",
            link: function(scope, element, attrs, ngModel) {
                var dateFormat;
                attrs.$observe("dateParser", function(value) {
                    dateFormat = value;
                    ngModel.$render();
                });
                ngModel.$parsers.unshift(function(viewValue) {

in

    angular.module("dateParser").directive("dateParser", [ "dateFilter", "$dateParser", "$locale", function(dateFilter, $dateParser, $locale) {
        "use strict";
        return {
            restrict: "A",
            require: "ngModel",
            link: function(scope, element, attrs, ngModel) {
                var dateFormat;
                attrs.$observe("dateParser", function(value) {
                    dateFormat = value;
                    ngModel.$render();
                });
                scope.$watch(
                    function() {
                        return $locale.id;
                    },
                    function(newValue, oldValue, scope) {
                        if (angular.isDefined(dateFormat)) {
                         ngModel.$render();
                        }
                    }
                );
                ngModel.$parsers.unshift(function(viewValue) {

Ciao Angelo

**Comment by dnasir** [comment]
@ardf69 Yea, I've been wanting to merge a pull request that addresses this issue. Just haven't had the time. Now I have a reason to actually get it done ;-)

**Comment by dnasir** [comment]
This has been resolved in the latest version, albeit still in beta.
