### ISSUE TITLE
What is the depency name for this...?

### ISSUE THREAD

**Issue by neilhanekom** [dnasir/angular-dateParser#34]
Should I add this to angular module depency? What is the name of the depency? How do I use it in my controllers?

**Comment by dnasir** [comment]
@neilhanekom I'm not sure I follow. If you're trying to use the parser itself, have a look at the directive code to see how it's included as a dependency.

**Comment by sebrojas14** [comment]
Is dateParser...so you need to add ir as 'dateParser' when you declare your module
