### ISSUE TITLE
Missing "main" from bower.js

### ISSUE THREAD

**Issue by markygab** [dnasir/angular-dateParser#35]
Please add the following to your bowe.js to allow plugins like grunt wiredep to pick up your excelent plugin

"main": "./dist/angular-dateparser.min.js",

**Comment by markygab** [comment]
Sorry, you've done it already, but not yet released!

**Comment by dnasir** [comment]
@markygab Yea, I haven't released it yet. I thought I could release it with some other fixes I have in my backlog. If you really need this, please download manually from the repo. It will be included in the next release anyway :-)

**Comment by brunobastosg** [comment]
Just commenting here to share my workaround. Since this fix is not released yet, I had to specify the commit with its hash in bower.json:

    "angular-dateParser": "dnasir/angular-dateParser#bd1895adfdd35e565777032a1fde50c4163d5281"

**Comment by dnasir** [comment]
This has been resolved in the latest release, albeit still in beta.
