### ISSUE TITLE
Issue parsing depending on today's date?

### ISSUE THREAD

**Issue by leviwilson** [dnasir/angular-dateParser#36]
We have a spec about parsing `12/31/9999` (doesn't matter why). Yesterday (5/31/2015) when we call `$dateParser.parse('12/31/1999')` it returns a valid date. Today (6/1/2015) it returns `undefined`.

If I change my calendar back to yesterday, the spec passes.

Any idea?

**Comment by walterg2** [comment]
Additionally, if you test with your date clock set to a day in February, the max date you can parse is `12/29/9999`.

**Comment by leviwilson** [comment]
I'm dumb; our specs had a stupid format and we only _just now_ noticed it. Please disregard.
