### ISSUE TITLE
make possible to parse dates to UTC

### ISSUE THREAD

**Issue by antonnikolaev** [dnasir/angular-dateParser#44]
There is some scenarios when local time zone should be ignored taking the UTC time as model. 
One of the cases I see is when we need to parse dates without time with patterns like 'MMM dd, yyyy'.

**Comment by dnasir** [comment]
@antonnikolaev The purpose of this module is to provide the ability to reverse the stuff done by the angular date filter. If you provide the ``Z`` format string, you can control which timezone your code uses. i.e. ``MMM dd, yyyy Z``

On the other hand, it's not that difficult to include the ability to set this up in the app ``.config()`` method.

**Comment by dnasir** [comment]
On second thought, I don't think this is a suitable feature to implement, as it will increase the complexity of this simple parser. Just use the ``Z`` format string if you need to handle timezones.
