### ISSUE TITLE
Invalid meta in bower.json

### ISSUE THREAD

**Issue by brunobastosg** [dnasir/angular-dateParser#45]
When I run `bower install angular-dateParser --save`, I get:

    bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
    bower invalid-meta  The "main" field cannot contain minified files
    bower invalid-meta  The "main" field cannot contain minified files
    bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .js files: ["./dist/angular-dateparser.js","./dist/angular-dateparser.min.js"]
    bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .map files: ["./dist/angular-dateparser.js.map","./dist/angular-dateparser.min.js.map"]

Because of that, wiredep adds `angular-dateparser.js` and `angular-dateparser.min.js` to my `index.html`.

I had to override bower.json to make this work.

**Comment by dnasir** [comment]
Thanks for the info. I'll look into this.

**Comment by dnasir** [comment]
Should now be fixed.

**Comment by brunobastosg** [comment]
Thanks!
