### ISSUE TITLE
Visual Studio crashes when debugging IE

### ISSUE THREAD

**Issue by henkdehaan** [dnasir/angular-dateParser#48]
When using angular-dateparser.js version 1.1.1 we get a crash of Visual Studio 2015 when starting Internet Explorer 11 from within the development environment using the 'Start debugging' (F5) command.

We have retrieved the library from the Bower repository and the problem probably has something to do with the angular-dateparser.js.map file (which references the TypeScript sources that are not in the dist folder). Putting the  DateParser.ts and DateParserDirective.ts in the dist folder solves the problem.

**Comment by dnasir** [comment]
@henkdehaan This is most likely due to the ``sourceroot`` path pointing to the wrong location. I've added source content into the sourcemaps so you should no longer have this issue. Let me know if you're still having trouble with this.
