### ISSUE TITLE
Redundant dependencies in package.json

### ISSUE THREAD

**Issue by L2jLiga** [dnasir/angular-dateParser#51]
I guess ts-loader, typescript, webpack should be in devDependencies.
I don't know any reasons to keep they in dependencies.

**Comment by L2jLiga** [comment]
@dnasir any updates?

**Comment by dnasir** [comment]
Hey. Sorry for the slow response. This is a really old project and I've moved on from Angular now.

I can fix this issue, but there will be no future development for this project after that.

You're free to submit a pull request, though.
